# SPDX-FileCopyrightText: 2026 openDesk Edu Contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grommunio.fullname" . }}-secret
  labels:
{{ include "grommunio.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.grommunio.db.password }}
  GROMMUNIO_DB_PASSWORD: {{ .Values.grommunio.db.password | quote }}
  {{- end }}
  {{- if .Values.grommunio.cache.password }}
  GROMMUNIO_CACHE_PASSWORD: {{ .Values.grommunio.cache.password | quote }}
  {{- end }}
  {{- if .Values.grommunio.auth.oidc.clientSecret }}
  GROMMUNIO_OIDC_CLIENT_SECRET: {{ .Values.grommunio.auth.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.grommunio.auth.saml.identityProviderCert }}
  GROMMUNIO_SAML_IDP_CERT: {{ .Values.grommunio.auth.saml.identityProviderCert | quote }}
  {{- end }}
  {{- if .Values.grommunio.ldap.bindPassword }}
  GROMMUNIO_LDAP_BIND_PASSWORD: {{ .Values.grommunio.ldap.bindPassword | quote }}
  {{- end }}
